name: Run Jest Tests

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: |
          cd server
          npm install

      - name: Set up environment variables
        run: |
          echo "DB_URL=mongodb://exampleUser:examplePass@localhost:27017/test" >> $GITHUB_ENV
          echo "DB_PASS=examplePass" >> $GITHUB_ENV
          echo "NODE_ENV=production" >> $GITHUB_ENV

      - name: Run tests
        run: |
          cd server
          npm test
