name: Run Jest Tests

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: |
          cd server
          npm install

      - name: Set up environment variables
        run: |
          echo "DB_URL=${{ secrets.DB_URL }}" >> server/.env
          echo "DB_PASS=${{ secrets.DB_PASS }}" >> server/.env
          echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> server/.env
          cat server/.env  # Output to logs for debugging

      - name: Run tests
        run: |
          cd server
          node -r dotenv/config node_modules/.bin/jest --runInBand  # Load dotenv explicitly
